### ISSUE TITLE
Leanplum.start does not have an onComplete callback for React Native library

### ISSUE THREAD

**Issue by defualt** [Leanplum/Leanplum-ReactNative-SDK#11]
"@leanplum/react-native-sdk": "1.0.12"
For `leanplum-sdk` for web, `Leanplum.start` has an argument for an onReady handler like this.

```
Leanplum.start(() => doStuff());
```

`@leanplum/react-native-sdk` does not support this callback.

In general, it seems like the interface for `leanplum-sdk` and `@leanplum/react-native-sdk` should be the same to the same codebash can support iOs, Android, and additionally web, with minimal glue.

**Comment by defualt** [comment]
This is my current implementation after just discovering `addStartResponseHandler` and `onStartResponse`.  It would be helpful to have `onStartResponse` and `addStartResponseHandler` in each of the other's interfaces.

```
const startLeanPlum = () => {
  return new Promise((resolve,reject) => {
    try {
      if (isWeb) {
        Leanplum.addStartResponseHandler(resolve);
      } else {
        Leanplum.onStartResponse(resolve);
      }
      Leanplum.start();
    } catch (e) {
      reject(e);
    }
  });
};
```

**Comment by milos1290** [comment]
The RN SDK is a wrapper for iOS/Android so the API is more align to those SDKs. Can we close this issue ?

**Comment by defualt** [comment]
Close if you want the APIs to have needless variation across platforms which requires implementations of `react-native`+`react-native-web` apps to include extra glue code.

**Comment by e7mac** [comment]
Parity in the API for JS and RN is a bigger project and will be on the roadmap.
