### ISSUE TITLE
Leanplum.getVariables does not work

### ISSUE THREAD

**Issue by defualt** [Leanplum/Leanplum-ReactNative-SDK#12]
"@leanplum/react-native-sdk": "1.0.12"

```
const leanPlumVariables = await Leanplum.getVariables();
```
leanPlumVariables is empty object with `@leanplum/react-native-sdk ` but has my variables for A/B testing populated in web with `leanplum-sdk`

  _

```
const singleLeanPlumVariable = await Leanplum.getVariables('some_variable_setup_in_leanplum_dashboard');
```
singleLeanPlumVariable is undefined with `@leanplum/react-native-sdk ` but has an appropriate value for A/B testing in web with `leanplum-sdk`

**Comment by milos1290** [comment]
For variables to be populated you need to define them first. The behavior is same as in Android/iOS SDK.

```
const vars = {
  myStringVar: 'string var default value',
  myNumVar: 12,
  myBoolVar: true
}
...
Leanplum.setVariables(vars);
Leanplum.start();
...
await Leanplum.getVariables();
```

Calling it before start will register variable, so when `start` call or `forceContentUpdate` is called it will update the existing registered variables. 
NOTE that variables wont exist and be populated unless they are set first with `Leanplum.setVariables`.

**Comment by defualt** [comment]
I set the variables in the Leanplum web portal (screenshot below).  This is for A/B testing.  What's the point of that web interface if I would have to calculate the distribution of variants on the client?  What would the point of `getVariables` be if I am supposed to set A/B test variables in the client already?  The sdk for web `leanplum-sdk` doesn't have this problem: the A/B test variables are retrieved via `getVariables` without a problem.  It would be surprising if this were an intentional product difference between `@leanplum/react-native-sdk` and `leanplum-sdk`.


![image](https://user-images.githubusercontent.com/399135/85728767-3956ef80-b6c6-11ea-9199-6563cb9ab107.png)

**Comment by milos1290** [comment]
The `setVariables` will create object on native side that will keep track of state of the that particular variable and update its value when SDK starts or updates. In iOS/Android and ReactNative we do not provide a way to return all defined variables directly, instead those variables need to be defined in client code that will act as hooks to the one on dashboard.

Hope this clears it a bit.

**Comment by defualt** [comment]
Ok, that seems to work.  I set key/values in an object in `setVariables`, and then when I do `getVariables` the values are different, so I assume the server is providing appropriate A/B test variation.

It is a confusing API.  It seems that I should instead be passing an array of keys to `setVariables` instead of an object because the values within that object are irrelevant... they just get overwritten after `getVariables`.  When I specify a value in code, I expect it mean something, but they doesn't here, they just have to exist.  It's also frustrating that `@leanplum/react-native-sdk` and `leanplum-sdk` behave differently with this feature.

**Comment by milos1290** [comment]
The values you provide initially are default values, i.e if network call fails and you request variables with `getVariables` it will return default values you initially set with `setVariables`. This is to make sure that you don't enter invalid state where variable have unknown value.

**Comment by defualt** [comment]
That makes sense. It is not clear from the docs.  Thanks for your help.

**Comment by milos1290** [comment]
@defualt Since ReactNative is wrapper for Android and iOS SDK, you can in most cases check the docs for one of those to make sure you are on correct path.

**Comment by defualt** [comment]
I suggest you make the React Native documentation as explicit as any other platform.  Many React Native developers such as myself have limited background in vanilla iOs and Android development so it's harder for us to parse non-JS docs, and we assume React Native libraries are supported with documentation at the same level as other platforms for a product.

**Comment by milos1290** [comment]
@defualt Thanks for the feedback, we will make sure to create step by step guide for integration.

I'll close this issue.
