### ISSUE TITLE
Pod install fails - SWIFT_VERSION missing

### ISSUE THREAD

**Issue by Ingibjorg** [Leanplum/Leanplum-ReactNative-SDK#15]
Pod install fails with the following message in and Obj-C based React Native project:

```
Installing react-native-leanplum (1.0.13)
[!] Unable to determine Swift version for the following pods:

- `react-native-leanplum` does not specify a Swift version and none of the targets (`xxx`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

**Steps to reproduce:**
```
yarn add @leanplum/react-native-sdk
npx react-native link @leanplum/react-native-sdk
cd ios
pod install
```

Side note:
Why isn't the library set up for autolinking? Autolinking is the new standard now: https://reactnative.dev/blog/2019/07/03/version-60#native-modules-are-now-autolinked

**Comment by milos1290** [comment]
Thanks for the feedback,

The error you are seeing occurs if you are trying to import library into a target that doesn't actually use Swift. Try setting Swift version in your target in XCode

As for autolinking, it is supported out of the box, if you are using ReactNative version 0.60+ you don't have to link manually, you can find more details [here](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md)

**Comment by Ingibjorg** [comment]
Thanks @milos1290 . I had to update my project from 0.62 to 0.63 and fix the Swift setup to get this working properly.
