### ISSUE TITLE
Android Setup

### ISSUE THREAD

**Issue by defualt** [Leanplum/Leanplum-ReactNative-SDK#17]
Hopefully future versions of this library will support auto-linking.

Until then, can you detail how to do the setup for Android?  

I'm trying to setup MainApplication.java as discussed here:
https://github.com/Leanplum/Leanplum-ReactNative-SDK/issues/13

But I don't know what to to import at the top of the file.  

I get these errors where building for development:
```
/my-app/android/app/src/main/java/com/company/MyApp/MainApplication.java:86: error: cannot find symbol
    Leanplum.setApplicationContext(this);
    ^
  symbol:   variable Leanplum
  location: class MainApplication
/my-app/android/app/src/main/java/com/company/MyApp/MainApplication.java:87: error: cannot find symbol
    LeanplumActivityHelper.enableLifecycleCallbacks(this);
    ^
  symbol:   variable LeanplumActivityHelper
  location: class MainApplication
Note: /Users/brianephraim/Sites/ted/masterclass-beta/android/app/src/debug/java/com/ted/B2CMasterclass/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by milos1290** [comment]
@defualt [Here](https://docs.leanplum.com/reference#section-additional-android-setup) is updated doc which contains more information on how to implement SDK properly

**Comment by defualt** [comment]
I had to do some additional things to get this to work.

Add `implementation 'com.leanplum:leanplum-core:5.4.1'` to `dependencies {` in `android/app/build.gradle`.

Add `import com.leanplum.annotations.Parser;` to `MainApplication.java`.

**Comment by MaganAnkur** [comment]
I am also getting the build failure:

symbol:   class RemoteMessage
  location: package com.google.firebase.messaging
/Users/test/Documents/GitHub/proj/android/app/src/main/java/com/name/app/leanplum/Custom_FirebaseMessagingService.java:6: error: cannot find symbol
import com.leanplum.LeanplumPushFirebaseMessagingService;
                   ^
  symbol:   class LeanplumPushFirebaseMessagingService
  location: package com.leanplum
/Users/test/Documents/GitHub/proj/android/app/src/main/java/com/name/app/leanplum/Custom_FirebaseMessagingService.java:7: error: cannot find symbol
import com.leanplum.LeanplumPushNotificationCustomizer;
                   ^
  symbol:   class LeanplumPushNotificationCustomizer
  location: package com.leanplum
/Users/test/Documents/GitHub/proj/android/app/src/main/java/com/name/app/leanplum/Custom_FirebaseMessagingService.java:8: error: cannot find symbol
import com.leanplum.LeanplumPushService;
                   ^
  symbol:   class LeanplumPushService
  location: package com.leanplum
/Users/test/Documents/GitHub/proj/android/app/src/main/java/com/name/app/leanplum/Custom_FirebaseMessagingService.java:9: error: cannot find symbol
import com.leanplum.LeanplumPushFirebaseMessagingService;
                   ^
  symbol:   class LeanplumPushFirebaseMessagingService
  location: package com.leanplum
/Users/test/Documents/GitHub/proj/android/app/src/main/java/com/name/app/leanplum/Custom_FirebaseMessagingService.java:15: error: cannot find symbol
public class Custom_FirebaseMessagingService extends LeanplumPushFirebaseMessagingService {
                                                     ^
  symbol: class LeanplumPushFirebaseMessagingService
/Users/test/Documents/GitHub/proj/android/app/src/main/java/com/name/app/leanplum/Custom_FirebaseMessagingService.java:18: error: cannot find symbol
    public void onMessageReceived(RemoteMessage remoteMessage) {
                                  ^
  symbol:   class RemoteMessage
  location: class Custom_FirebaseMessagingService
/Users/test/Documents/GitHub/proj/android/app/src/main/java/com/name/app/leanplum/Custom_FirebaseMessagingService.java:17: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/test/Documents/GitHub/proj/android/app/src/main/java/com/name/app/leanplum/Custom_FirebaseMessagingService.java:26: error: cannot find symbol
            super.onMessageReceived(remoteMessage);
            ^
  symbol:   variable super
  location: class Custom_FirebaseMessagingService
9 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 33s

    at checkExecSyncError (child_process.js:611:11)
    at execFileSync (child_process.js:629:15)
    at runOnAllDevices (/Users/test/Documents/GitHub/proj/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/Users/test/Documents/GitHub/proj/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at /Users/test/Documents/GitHub/proj/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.handleAction (/Users/test/Documents/GitHub/proj/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:164:9

**Comment by milos1290** [comment]
@MaganAnkur It seems you are missing Leanplum FCM dependency, you can find more info [here](https://docs.leanplum.com/reference#section-android-setup)

@defualt I'll double check again, the `leanplum-core` should be added by autolinking.

**Comment by MaganAnkur** [comment]
Thanks @milos1290 for your response though I found out that I had missed Leanplum FCM dependency but it would be good it gets added by autolinking. Thanks

**Comment by milos1290** [comment]
@MaganAnkur Great to hear. Unfortunately  it is not possible to add it since its optional dependency and not everyone needs it.

**Comment by brunoccc** [comment]
> @MaganAnkur Great to hear. Unfortunately it is not possible to add it since its optional dependency and not everyone needs it.

I undertand that, but could you please add to the documentation [here](https://docs.leanplum.com/reference#section-additional-android-setup) that we need to add some dependancies in the gradle file? By reading that document it seems that everything works out of the box simply by npm installing the package, but when you try to follow the Additional Android Setup you are left with unresolved imports. 
I wasted hours before eventually finding @defualt answer above (Thank you, defualt!), also because it's hidden in a closed issue that I never thought could affect me installing the package months later.
