### ISSUE TITLE
JSON value '<JSON>' of type NSString cannot be converted to NSDictionary

### ISSUE THREAD

**Issue by MaganAnkur** [Leanplum/Leanplum-ReactNative-SDK#19]
After implementing Leanplum SDK I am getting below issue:

![Screen Shot 2020-07-08 at 9 12 44 AM](https://user-images.githubusercontent.com/42070594/86956093-8e631e80-c126-11ea-83b4-f8228a32d7d7.png)

**Error Log From XCode:**

[error][tid:com.facebook.react.LeanplumQueue][RCTConvert.m:55] JSON value 'Aa8VbmUJgBNLpIES2FMO8aApf2E2' of type NSString cannot be converted to NSDictionary

**Comment by MaganAnkur** [comment]
Any help on above pls.

**Comment by milos1290** [comment]
Hey,
Do you mind sharing your Leanplum SDK implementation code ?

**Comment by MaganAnkur** [comment]
@milos1290 
import Config from 'react-native-config';
import Mixpanel from 'react-native-mixpanel';
import {Leanplum, LeanplumInbox} from '@leanplum/react-native-sdk';
import firebase from '@react-native-firebase/app';
import axios from 'axios';
import DeviceInfo from 'react-native-device-info';

class LeanplumAnalyticsManager {
  initialized = false
  uid = null

  constructor() {
    this.initialize();
  }

  initialize = async () => {
    if (this.initialized) {
      return;
    }

    const {
      LEANPLUM_APP_ID: appId,
      LEANPLUM_DEV_KEY: devKey,
      LEANPLUM_PROD_KEY: prodKey,
      LEANPLUM_MODE: mode,
    } = Config;
    if (mode === 'debug') {
      Leanplum.setAppIdForDevelopmentMode(appId, devKey);
    } else {
      Leanplum.setAppIdForProductionMode(appId, prodKey);
    }

    //const hasStarted = await Leanplum.hasStarted();
    //if (!hasStarted) {
      Leanplum.start();
    //}

    this.setCurrentUser();
    this.initialized = true;
  }

  // TODO: implement logout

  setCurrentUser = () => {
    const currentUser = firebase.auth().currentUser;
    if (currentUser && currentUser.uid) {
      this.uid = currentUser.uid;
    }
  }

  leanplum = async callback => {
    if (!this.initialized) {
      await this.initialize();
    }

    return await callback();
  }

  track = async (event, properties) => {
    return await this.leanplum(
      async () =>
        await Leanplum.track(
          event,
          undefined,
          undefined,
          this.sanitizeProperties(properties),
        ),
    );
  }

**Comment by MaganAnkur** [comment]
@milos1290 any suggestion pls?

**Comment by milos1290** [comment]
@MaganAnkur can you double check your `sanitizeProperties` method ? it seems you are passing string instead of dictionary to `Leanplum.track` method. Also this seems wrong

```
Leanplum.track(
event,
undefined,
undefined,
this.sanitizeProperties(properties),
)
```
method signature is:
`Leanplum.track(event: string, params: Dictionary);`

**Comment by MaganAnkur** [comment]
Thanks @milos1290 for your response but I got the issue it was while setting the user, there was arguments mismatch. Closing this now.
