### ISSUE TITLE
getVariables not returning complete structure

### ISSUE THREAD

**Issue by Matzielab** [Leanplum/Leanplum-ReactNative-SDK#24]
First i set variables via the Leanplum.setVariables({...vars}) method, then i set a Leanplum.onVariablesChanged then i start. Inside the Leanplum.onVariablesChanged i call getVariables but it doesnt get the complete set, only top level? what is going on?

```
  // first variables is a complex object with nested objects example like this:

  let variables = {"featureIntros": {"intro1": {"title": "TITLE", "body": [Object]}...}

  await Leanplum.setVariables(variables);

  await Leanplum.onVariablesChanged(async () => {
    let vars = await Leanplum.getVariables();

    // When getting the variables somehow its only toplevel where everything is just an empty object
    // vars = {"featureIntros":  {}}

  });

  await Leanplum.start();

**Comment by Matzielab** [comment]
@milos1290 This is on android btw, and 1 out of 100 it actually returns the full structure but then it suddenly fails again, hard to rely on

**Comment by Matzielab** [comment]
Further debugging and it seems to not work with react-natives hot reload. Im not that skilled in java but from what i can see it seems like something is happening in the Var.define function when reading from cache

**Comment by CyberMew** [comment]
Which sdk version are you using?

**Comment by Matzielab** [comment]
@CyberMew React Native SDK 1.1.0

**Comment by milos1290** [comment]
@Matzielab Strange, i'll check it out and see whats going on

**Comment by milos1290** [comment]
@Matzielab I've tried to reproduce the issue on a clean app with cold start (no hot reloads), basically like a plain android app, but the issue is not visible at all. I suspect it might be the issue with react native environment.
