### ISSUE TITLE
'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by jgalianoz** [Leanplum/Leanplum-ReactNative-SDK#27]
I have this problem, any idea how to solve this? 🙏 

![image](https://user-images.githubusercontent.com/12010942/95274055-6741e900-080a-11eb-90bb-6bcb1467f06e.png)

![image](https://user-images.githubusercontent.com/12010942/95268273-9a7d7b80-07fc-11eb-9000-87a72a782e48.png)

**Comment by nzagorchev** [comment]
Hi Manuel,
This does not seem to be caused by our SDK in particular. 

You can try re-installing the pods and also check this thread:
https://stackoverflow.com/questions/53541573/build-failed-react-rctbridgemodule-h-file-not-found
https://stackoverflow.com/questions/41663002/react-rctbridgemodule-h-file-not-found

**Comment by jgalianoz** [comment]
@nzagorchev Thanks for your response:

I follow the first article but I received this error 😢

Any idea about this?

Thanks.

![image](https://user-images.githubusercontent.com/12010942/96152368-19944300-0ed2-11eb-98a3-32576e511868.png)

**Comment by zach-owens123** [comment]
Hi Manuel,  this looks like after installing those dependencies that you opened up the xcode project w/o those dependencies rather than the workspace with those.   otherwise you can try reinstalling the dependencies in your project

**Comment by jgalianoz** [comment]
I added the library manually but the Leanplum.h file not exist

![image](https://user-images.githubusercontent.com/12010942/96754985-b43fc680-1397-11eb-893e-0073a98e6d9b.png)

**Comment by zach-owens123** [comment]
thanks. did you follow the manual setup in our docs or how did you go about set up?

**Comment by zach-owens123** [comment]
try installing the pods directly in your project and open the workspace

**Comment by milos1290** [comment]
Please refer to this issue for a fix https://github.com/Leanplum/Leanplum-ReactNative-SDK/issues/30

**Comment by nzagorchev** [comment]
> Please refer to this issue for a fix #30
