### ISSUE TITLE
Boolean variables are converted to number values

### ISSUE THREAD

**Issue by tailorem** [Leanplum/Leanplum-ReactNative-SDK#31]
Variables that are set with a boolean value and are not nested within an object are being converted to numbers.
SDK version 1.1.1

```
const defaultVariables = {
  items: {
    colour: 'blue',
    size: 66,
    showBadges: true,
    falseBool: false,
  },
  showAds: true,
  isTrue: true,
  newBool: false,
};

Leanplum.setVariables(defaultVariables);
Leanplum.start();

const leanplumVariables = await Leanplum.getVariables();
console.log('\n\nleanplumVariables :>> ', leanplumVariables);
```

Console log:
```
leanplumVariables :>>  {"isTrue": 1, "items": {"colour": "blue", "falseBool": false, "showBadges": true, "size": 66}, "newBool": 0, "showAds": 1}
```

Dashboard:
<img width="678" alt="Screen Shot 2020-11-04 at 10 53 56 AM" src="https://user-images.githubusercontent.com/29444471/98156717-06e7ab00-1e8d-11eb-9f9f-9f65a74afc8c.png">

**Comment by milos1290** [comment]
@tailorem changing type from code won't work. You will have to change it on dashboard also. If the variable was defined as number first, it won't be redefined to bool. You will have to either delete it or change manually to correct type.
