### ISSUE TITLE
Android package name causes conflicts with other modules in release builds

### ISSUE THREAD

**Issue by tailorem** [Leanplum/Leanplum-ReactNative-SDK#32]
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.reactlibrary">

</manifest>
```
The package name `com.reactlibrary` is generic and causes conflicts with other modules (such as custom modules or other libraries that also use the default package name) resulting in build failures.

**Comment by nzagorchev** [comment]
https://github.com/Leanplum/Leanplum-ReactNative-SDK/pull/46
