### ISSUE TITLE
No work Open Action with iOS

### ISSUE THREAD

**Issue by nericode** [Leanplum/Leanplum-ReactNative-SDK#37]
When sending a notification with the action of "open action" this does not work correctly in a notification, specifically with deeplinkin.

If the notification does not have "Mute inside app" it shows an alert, which is the correct behavior and redirects correctly, but if that option is not selected and the phone has the app completely closed, the deeplinkin action will never open.

I use  `"@leanplum/react-native-sdk": "^1.1.1"`

Any idea @milos1290

**Comment by dejan2k** [comment]
Hi @nericode 
we have this issue with open action on iOS 13 and currently working on a fix for it.
Can you please check on which iOS version/versions you have this issue?

**Comment by nericode** [comment]
Hi @dejan2k thanks for your help, 

We test in:

iPhone SE - 14.0.1
iPhone 8 - 14.0.1
iPhone 11 - 14.3

**Comment by AbdullahMH95** [comment]
@dejan2k Any update on this issue please?

**Comment by nzagorchev** [comment]
Hi,

I have additional questions:
1. Does it work for a web URL (not a deeplink)?
2. Does it work if the app is in the background?
3. Is the Open event tracked in Leanplum for the user in this case?

**Comment by nericode** [comment]
Hi @nzagorchev 

Does it work for a web URL (not a deeplink)?
YES
Does it work if the app is in the background?
NO
Is the Open event tracked in Leanplum for the user in this case?
NO

**Comment by dejan2k** [comment]
The fix for this issue will be included in our next release.
The problem was in our native iOS SDK and the fix is applied [here](https://github.com/Leanplum/Leanplum-iOS-SDK/pull/432)
