### ISSUE TITLE
Open Action not working on Android  11 

### ISSUE THREAD

**Issue by wadesun18** [Leanplum/Leanplum-ReactNative-SDK#38]
When calling LeanplumInbox.read(messageId), it should to trigger open action to open an external url. It works on Android 10 or below but not Android 11. I was using version `1.0.13` and I tried upgrading to the latest version `1.1.1` and it's still the same. Thanks!

**Comment by milos1290** [comment]
I've tested this on Android 11 and cannot get it to reproduce. The open action is always executed when i read the inbox message. Can you provide more information on how to reproduce this ?

**Comment by wadesun18** [comment]
Thanks for the response @milos1290, I am still seeing this on Android 11 but works fine on everything else. The way I configured this on leanplum is open action and open URL then I set an URL. Please note that if the url is a deeplink then it works by taking me to somewhere else in the app. If the URL is a link outside of the app, then nothing happens and no error messages either. I am using "@leanplum/react-native-sdk": "^1.1.1" and "react-native": "0.63.4".  Let me know if there's more information you might need, thanks again!
