### ISSUE TITLE
Push Token not registered as expected.

### ISSUE THREAD

**Issue by nzwnabdulwahid** [Leanplum/Leanplum-ReactNative-SDK#42]
Hello everyone, I have an issue I encounter since last week, where **Push Token** from the devices not being registered as expected. 

Necessary library has been added. Is there any way to add it manually or to actually debug what happens ?

`@leanplum/react-native-sdk": "1.0.13`, `com.leanplum:leanplum-fcm:5.3.3` and `com.google.firebase:firebase-messaging:20.1.4` is the related package that I'm using.

**Comment by milos1290** [comment]
Hi @nzwnabdulwahid 

Was it working before ? 
Also, you can try updating @leanplum/react-native-sdk to latest version and see if that fixes the issue.
