### ISSUE TITLE
gradle 7.0 and above requires use of maven-publish not maven gradle plugin

### ISSUE THREAD

**Issue by JeremyGreen-TomTom** [Leanplum/Leanplum-ReactNative-SDK#57]
https://docs.gradle.org/7.0/userguide/upgrading_version_6.html#removal_of_the_legacy_maven_plugin

...so an app using gradle 7.0 or above fails to build.

```
Build file 'node_modules/@leanplum/react-native-sdk/android/build.gradle' line: 23
A problem occurred evaluating project ':leanplum_react-native-sdk'.
> Plugin with id 'maven' not found.
```

This build error is for @leanplum/react-native-sdk 1.2.0 and gradle 7.3.3, but https://github.com/Leanplum/Leanplum-ReactNative-SDK/blob/master/android/build.gradle is still using "maven" not "maven-publish".

**Comment by nericode** [comment]
I have same issue

**Comment by hborisoff** [comment]
I'm currently working on that Gradle issue and I'll remove the publishing code, as it seems to be redundant.

You can check the changes [here](https://github.com/Leanplum/Leanplum-ReactNative-SDK/compare/master..feature/SDK-637_update_gradle).

**Comment by ThushalIntervest** [comment]
@Bej-Technologies  did you found any for this?

`Could not find method mavenDeployer()`

Gradle Version =  gradle-7.3.3

**Comment by hborisoff** [comment]
@ThushalIntervest
Unfortunately RN SDK 1.3.0 is tested only using the Gradle 7.2.
We haven't updated to the newest version yet.

**Comment by SleepingProgrammer** [comment]
I'd hate to necro but any updates with this?
