### ISSUE TITLE
Outdated README

### ISSUE THREAD

**Issue by barsumek** [Leanplum/Leanplum-ReactNative-SDK#6]
In README the steps to install the app are:

`yarn add react-native-leanplum` or `npm install react-native-leanplum`

but this command will install the old package: https://www.npmjs.com/package/react-native-leanplum which looks like an old test version of the SDK (`Test` in `package.json` etc.)

The correct lib is this one: https://www.npmjs.com/package/@leanplum/react-native-sdk and the command should look like this: `yarn add @leanplum/react-native-sdk`.

Also, the usage example in the README:
```js
import {Leanplum, LeanplumInbox} from 'react-native-leanplum';
 
// TODO: What to do with the module?
Leanplum.setAppIdForDevelopmentMode('APP_ID', 'DEVELOPMENT_KEY');
Leanplum.start();
const inbox = await LeanplumInbox.inbox();
```
with `TODO` in it does not encourage to install the SDK.

It would be nice to update the README with proper steps (please take a look at this issue too: https://github.com/Leanplum/Leanplum-ReactNative-SDK/issues/4) and better usage examples. Right now some users might install the incorrect version by accident if they follow the README.

**Comment by e7mac** [comment]
thanks for the suggestions!
