### ISSUE TITLE
Not show Interestitial

### ISSUE THREAD

**Issue by nericode** [Leanplum/Leanplum-ReactNative-SDK#61]
I have configure a interestitial when:

**Display Trigger**: Event {EventName} triggers

But i have this issue: 

![Screen Shot 2022-03-02 at 11 14 12 AM](https://user-images.githubusercontent.com/7475549/156412991-6cc66723-8f15-4cc6-98f5-a3ec9ed7d65d.png)

**Comment by hborisoff** [comment]
@nericode
Please contact our support team about that issue.
