### ISSUE TITLE
Fatal Exception: java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by nericode** [Leanplum/Leanplum-ReactNative-SDK#62]
Hi team, when run the app, we have this error:

Class 'org.apache.http.message.BufferedHeader' does not implement interface 'org.apache.http.NameValuePair' in call to 'java.lang.String org.apache.http.NameValuePair.getName()' (declaration of 'com.leanplum.internal.WebSocketClient$1' appears in /data/app/~~AJe1R8MC6TWaETB2lzFuIA==/com.XXX.XXXX-TNFxsWZIKrV9kCDfp83BuA==/base.apk!classes2.dex)

**Comment by hborisoff** [comment]
@nericode 
Can you give more specifics, because it is the first time I see that error?
I searched through the Leanplum Android SDK and it is the socket client, used in development mode, that contains WebSocketClient class. And that `NameValuePair`  is coming from `org.apache.http.legacy` package.

**Comment by hborisoff** [comment]
Could you exclude from obfuscation the files from `com.leanplum.*` package and also the `org.apache.http.legacy` files, to assure that Proguard won't do anything that could cause the runtime exception?
Probably something like:
```
-keep class com.leanplum.** { *; }
-keep class org.apache.http.** { *; }
```
