### ISSUE TITLE
Opened Action not triggered when the app is foregrounded on iOS

### ISSUE THREAD

**Issue by Bej-Technologies** [Leanplum/Leanplum-ReactNative-SDK#67]
When I receive a status bar notification while the app is foregrounded on iOS nothing happens when I press it, even though I have set an Opened Action. The status bar notification works flawlessly if the app is in the background. I have traced it down to this code snippet:

```
if ([[UIApplication sharedApplication] applicationState] != UIApplicationStateActive) {
    [Leanplum onStartIssued:^() {
        if ([self areActionsEmbedded:userInfo]) {
            onContent();
        } else {
            [self requireMessageContent:messageId withCompletionBlock:onContent];
        }
    }];
} else {
    if (messageId && completionHandler) {
        completionHandler(UIBackgroundFetchResultNoData);
    }
}
```

Not sure why the action should be ignored if the app is in the foreground?

**Comment by nzagorchev** [comment]
What version of the SDK are you using? I believe this should be working as you expect in 4.0.0 and above since we rewrote the notifications logic. Would it be possible to update a sample app and give it a try?

**Comment by Bej-Technologies** [comment]
I'm using `"@leanplum/react-native-sdk": "^1.2.1"`. Will test upgrading :D

**Comment by Bej-Technologies** [comment]
Upgrading to 1.3.0 worked for me, thank you @nzagorchev!
