### ISSUE TITLE
onStartResponse listener does not work on Android

### ISSUE THREAD

**Issue by barsumek** [Leanplum/Leanplum-ReactNative-SDK#7]
According to the docs, the correct way to start Leanplum is to:
1. Call `Leanplum.start()`
2. Add `Leanplum.onStartResponse` listener and e.g. show Splash screen until it's called with `true` or `false`.

However, the listener does not fire on Android at all.

I played with it a bit and it looks like the listener is added correctly on the native side (`addStartResponseHandler` in `LeanplumModule.java`) but the callback handler is never called (`onResponse` method of `StartCallback`).

**Comment by e7mac** [comment]
Thanks for reporting the issue. I just tried this out with my test app and was able to get the `Leanplum.onStartResponse` to fire. Please could you take a look at these lines https://github.com/Leanplum/Rondo-ReactNative/blob/9586574086c14281803ae57ba20950adff3a7ea1/src/utils/startup.ts#L140-L145 and help me understand what might be different for you and how we can fix it?

**Comment by milos1290** [comment]
@barsumek also make sure that you set callback before calling `start` method.
