### ISSUE TITLE
Could not find react-native-0.71.0-rc.0-release.aar

### ISSUE THREAD

**Issue by DavidCS1995** [Leanplum/Leanplum-ReactNative-SDK#71]
Hello everyone. 

recently I'm a build the APK from React Native, but i have the next issues: 
Execution failed for task ':leanplum_react-native-sdk:generateReleaseRFile'.

Failed to transform react-native-0.71.0-rc.0-release.aar (com.facebook.react:react-native:0.71.0-rc.0) to match attributes {artifactType=android-symbol-with-package-name, com.android.build.api.attributes.BuildTypeAttr=release, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}  

Could not find react-native-0.71.0-rc.0-release.aar (com.facebook.react:react-native:0.71.0-rc.0).
        Searched in the following locations:
            https://repo.maven.apache.org/maven2/com/facebook/react/react-native/0.71.0-rc.0/react-native-0.71.0-rc.0-release.aar

when i go to the path, it says there is no such file.

Please, help me!

**Comment by hborisoff** [comment]
@DavidCS1995
Unfortunately this issue is not from our codebase:
https://github.com/facebook/react-native/issues/35210
Solution that worked on our side was to use the following in the Gradle files:
```
repositories {
    mavenCentral {
        // We don't want to fetch react-native from Maven Central
        // https://github.com/facebook/react-native/issues/35210
        content {
            excludeGroup "com.facebook.react"
        }
    }
}
```
And also make sure you use a 'fixed' version of react-native package, mentioned in the issue.
