### ISSUE TITLE
Android 13 - Push Notifications permission dialog not showing

### ISSUE THREAD

**Issue by hariomsharma-jmd** [Leanplum/Leanplum-ReactNative-SDK#74]
Push Notifications permission dialog not showing on Android 13.

**Comment by hborisoff** [comment]
@hariomsharma-jmd
Android 13 is supported in Leanplum Android SDK 7.1.0. We will be releasing Leanplum RN SDK with that version, but can't give you a specific date.
You can try manually updating manually to that version if you don't want to wait, but we don't encourage it.

**Comment by hariomsharma-jmd** [comment]
Hi @hborisoff Thanks for quick reply.

Do i need to chnage LEANPLUM_CT_SDK_VERSION also?

**Comment by hborisoff** [comment]
@hariomsharma-jmd Yes, you need to use 4.7.2. Check all changes [here](https://github.com/Leanplum/Leanplum-Android-SDK/releases/tag/7.1.0). In PR #536 there are few more things that needed to be bumped, like min SDK and Kotlin support.

**Comment by hariomsharma-jmd** [comment]
Okay, Thank you @hborisoff
