### ISSUE TITLE
Android - Push Notifications are not receiving after upgrading to RN 0.71.1

### ISSUE THREAD

**Issue by hariomsharma-jmd** [Leanplum/Leanplum-ReactNative-SDK#75]
Hello,

Push notification are not receiving on Android only after upgrading to React Native version 0.71.1

target android version is Android 12.

"@leanplum/react-native-sdk": "1.3.0"

Can you please help me?

**Comment by hborisoff** [comment]
@hariomsharma-jmd
I remember some issues with newer RN versions, but I think I fixed some of them in 2.0.0. Could you try to build with Leanplum RN SDK 2.0.0, so we can fix it in next release if issue persists?

**Comment by hariomsharma-jmd** [comment]
@hborisoff I am getting below error while installing pods

[!] CocoaPods could not find compatible versions for pod "CleverTap-iOS-SDK":
  In Podfile:
    clevertap-react-native (from `../node_modules/clevertap-react-native`) was resolved to 1.0.0, which depends on
      CleverTap-iOS-SDK (= 4.2.0)

    react-native-leanplum (from `../node_modules/@leanplum/react-native-sdk`) was resolved to 2.0.0, which depends on
      Leanplum-iOS-SDK (= 6.0.2) was resolved to 6.0.2, which depends on
        CleverTap-iOS-SDK (~> 4.1.5)

**Comment by nzagorchev** [comment]
react-native-leanplum 2.0.0 works with clevertap-react-native 0.9.4. 
clevertap-react-native 1.0.0 was released after that and bumped CleverTap-iOS-SDK to 4.2.0, where the Leanplum-iOS-SDK with this react native version, supports 4.1.x versions.

**Comment by hariomsharma-jmd** [comment]
@nzagorchev Thank you!

I will update the version and try again. 

I will update here if there will be any issue.
