### ISSUE TITLE
Calling Leanplum.userId() before Leanplum has started crashes the whole app

### ISSUE THREAD

**Issue by gusost** [Leanplum/Leanplum-ReactNative-SDK#77]
Only tested on iOS.
Documentation of course says it should be called after `start` but crashing the whole app instead of a milder error behaviour seems very dangerous.
Discovered via a temporary race condition.

Console yielded an uncaught exception and the app was terminated.

```shell
*** Terminating app due to uncaught exception 'Leanplum Error', reason: 'Leanplum: [Leanplum start] must be called before calling userId This error is only thrown in development mode.'
*** First throw call stack:
(0x198bede88 0x191f938d8 0x104d6e2e8 0x104d7ad9c 0x10455113c 0x198c58704 0x198c04b6c 0x198c04584 0x10423cc74 0x10423edec 0x10423ea74 0x1a01b84b4 0x1a01b9fdc 0x1a01c1694 0x1a01c21e0 0x1a01cce10 0x1e52c6df8 0x1e52c6b98) 
```

**Comment by nzagorchev** [comment]
Hi @gusost,

The exception is only thrown if using the Dev key, as stated in the error. The goal is to take the developer's attention.
The app will not crash in production and will just log an error in that case.
You can wrap such calls in the `Leanplum.onStartResponse` callback.

**Comment by gusost** [comment]
Aha! Did not get that it had to do with the dev key. I thought it had to do with a development build, which made me concerned since I saw it in a production build (where I forced the use of the dev key). 
Thank you
