### ISSUE TITLE
Not possible to use latest SDK along with latest version of clevertap SDK on iOS

### ISSUE THREAD

**Issue by jrobichaud** [Leanplum/Leanplum-ReactNative-SDK#84]
Hi,

I was updating the SDK and at the same time integrating the new dependency `clevertap-react-native` but I realized it is not possible to use the latest version of `clevertap-react-native` due to version resolving problems on iOS.

`@leanplum/react-native-sdk` 2.1.0 requires pod:
- `Leanplum-iOS-SDK`  =6.1.0
    - which requires pod `CleverTap-iOS-SDK` ~>5.0.1 (it means >=5.0.1,<5.1.0)

latest `clevertap-react-native` 1.2.1 requires pod
-  `CleverTap-iOS-SDK` =5.2.1

`CleverTap-iOS-SDK`'s version cannot be resolved with both `>=5.0.1,<5.1.0` and `=5.2.1`.

The most recent compatible  version of `clevertap-react-native` is 1.1.1 which uses `CleverTap-iOS-SDK` 5.0.1.

**Comment by nzagorchev** [comment]
Released [v2.2.0](https://github.com/Leanplum/Leanplum-ReactNative-SDK/releases/tag/2.2.0) with Leanplum iOS SDK 6.3.0, Leanplum Android SDK 7.3.0 and CleverTap ReactNative SDK 2.0.0
