### ISSUE TITLE
Only iOS - App freezes on Leanplum Campaigns In App Message 

### ISSUE THREAD

**Issue by dionisio28** [Leanplum/Leanplum-ReactNative-SDK#88]
I am encountering a significant issue on iOS where the screen freezes upon the appearance of a Leanplum In-App Message within our React Native application. This modal, intended for user campaigns, inhibits any screen interaction or the ability to dismiss the modal, rendering the app unusable while it is visible. The issue does not manifest on Android, where the modal functions correctly and does not impede user interaction.

### Steps to Reproduce

1. Open the application on an iOS device.
2. Trigger the campaign that launches the modal.
3. Observe that the app screen freezes and no interactions are possible.

### Expected Behavior

- The modal should appear without freezing the app, allowing user interaction and closure, similar to the behavior observed on Android devices.

### Actual Behavior

- The modal appears but freezes the entire app screen on iOS. No touches are registered, and it cannot be dismissed.

### System Information

- OS: macOS 14.4.1
- CPU: Apple M1 (arm64)
- Memory: 121.03 MB / 8.00 GB
- Node.js: 18.19.1
- Yarn: 1.22.21
- npm: 10.5.2
- Watchman: 2024.04.01.00
- CocoaPods: 1.13.0
- Xcode: 15.3 (15E204a)
- iOS SDK: 17.4
- React: 18.2.0
- React Native: 0.73.0
- Hermes enabled: Yes
- @leanplum/react-native-sdk: 2.2.0 or 2.3.0
- clevertap-react-native: 2.0.0 or 2.2.1

The Campaign for In App Message

![Screenshot 2024-05-03 at 10 39 16](https://github.com/Leanplum/Leanplum-ReactNative-SDK/assets/48914458/f040a023-834b-42f3-97db-3edcb39b5385)

Screenshots
![IMG_7270](https://github.com/Leanplum/Leanplum-ReactNative-SDK/assets/48914458/7903565f-5dd6-426e-bfe4-fb81dac573a1)
![IMG_7269](https://github.com/Leanplum/Leanplum-ReactNative-SDK/assets/48914458/1881559a-4b86-47e8-8221-1c2a8b81e944)

**Comment by nzagorchev** [comment]
Hi @dionisio28, we will try to reproduce this and get back to you.

**Comment by nzagorchev** [comment]
I see that you have connected with support already, lets keep the communication through there.

**Comment by dionisio28** [comment]
yeah make sense, I think we can close the ticket
